name: Update startTime on Merge to Main

on:
  push:
    branches:
      - main  # Trigger this workflow only when there's a push to the 'main' branch

jobs:
  update_start_time:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Check if trigram_daily_update is in commit message
      run: |
        # Get the commit message
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        
        # Check if trigram_daily_update is in the commit message
        if [[ "$COMMIT_MESSAGE" == *"trigram_daily_update"* ]]; then
          echo "Skipping startTime update, trigram update detected."
          exit 0
        fi

    - name: Update startTime in script.js
      run: |
        # Get current date in the desired format (ISO 8601 format)
        current_time=$(date --utc +'%Y-%m-%dT%H:%M:%SZ')

        # Use sed to replace the startTime in the script.js file with the current time
        sed -i "s/const startTime = new Date(\"[^\"]*\");/const startTime = new Date(\"$current_time\");/" script.js

    - name: Commit and push changes
      run: |
        git config user.name "comus3"
        git config user.email "come.plantin.carrenard@gmail.com"
        git fetch origin main
        git merge origin/main --no-edit || git reset --hard origin/main
        git add blog_script.js
        git commit -m "Update blog posts list"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
    